### ISSUE TITLE
Translate for spanish is possible

### ISSUE THREAD

**Issue by johnfelipe** [ministryofjustice/parliamentary-questions#310]
I can do that translation

**Comment by johnfelipe** [comment]
Its possible?

**Comment by johnfelipe** [comment]
Hi again,  its possible

**Comment by ashb** [comment]
Hi @johnfelipe,

We haven't done any work yet to enable internationalization so it might be slightly more than "just translating to spanish" but if you want to take this on and open a pull request that would be fantastic!

This guide <http://guides.rubyonrails.org/i18n.html> might give you some indication of the steps needed before you can on to the steps of creating the actual translations.

**Comment by johnfelipe** [comment]
Can you upload a example with **parliamentary-questions**, for my begin?

**Comment by johnfelipe** [comment]
Can you give me a little structure and example for begin that process

**Comment by johnfelipe** [comment]
If you explain a little i begin to work

**Comment by johnfelipe** [comment]
Hi again me, If you explain a little i begin to work
